# Group: CS16BTECH11016,CS16BTECH11021,CS16BTECH11015

In [1]:
import numpy as np

# This file takes inequalities from file 'input.txt'

In [2]:
inp  = np.genfromtxt("input.txt",)
print(inp)
N = inp
flag=0

[[ 1.  1. 50.]
 [ 2.  1. 30.]]


Separating 'b' from the taken input

In [3]:
b = N[:,-1]
print(b)
# b = b.transpose()
b = b.reshape(-1,1)
print(b)
N = np.delete(N,-1,1)
print(N)

[50. 30.]
[[50.]
 [30.]]
[[1. 1.]
 [2. 1.]]


adding slack variables to inequalities to make them equations

In [4]:
B = np.identity(len(inp), dtype = float) 
print(B)
res = np.concatenate((N,B),axis=1)
print(res)

[[1. 0.]
 [0. 1.]]
[[1. 1. 1. 0.]
 [2. 1. 0. 1.]]


# objective function is taken from file 'objective.txt'

In [5]:
cn = np.genfromtxt("objective.txt")
print(cn)

[2. 3.]


adding slack variables to objective function 

In [6]:
cb = np.zeros(len(inp))
print(cb)
z = np.concatenate((cn,cb),axis=0)
print(z)
B_inv = B

[0. 0.]
[2. 3. 0. 0.]


In [7]:
xn=[]
for i in range(len(N[0])):
    xn.append(i)
xb=[]
for i in range(len(inp)):
    xb.append(i+len(N[0]))
    
print(xn)
print(xb)
count = 0

[0, 1]
[2, 3]


# Traverse through vertices to find optimal solution

In [8]:
while(count<1000):
   
    n_array =res[:,xn[0]]
    n_array = n_array.reshape(-1,1)
    c_array =[]

    for i in xn:
        y = res[:,i]
        y = y.reshape(-1,1)
        n_array = np.concatenate((n_array,y),axis=1)
        c_array.append(z[i])
    n_array = np.delete(n_array,0,1)
    c_array = np.array(c_array)
#     print(n_array)
#     print(c_array)
    temp = np.matmul(B_inv,n_array)
    minx = np.amax(temp)
#     print(temp)
    if(minx<=0):
        print("unbounded")
        flag=1
        break
    tcb =[]
    for i in xb:
        tcb.append(z[i])
    tcb = np.array(tcb)
#     print(tcb)
#     print(xb)
    temp = np.matmul(tcb,temp)
    temp = np.subtract(temp,c_array)
    stopper = np.argmin(temp)
    if(temp[stopper]>=0):
        break
#     print("entering variable ",xn[stopper])

    x = res[:,xn[stopper]]
    x = x.reshape(-1,1)
#     print(x)
    temp1 = np.matmul(B_inv,x)
    temp2 = np.matmul(B_inv,b)
    for i in range(len(temp1)):
        temp2[i] = temp2[i]/temp1[i]
    
    

    m_index = np.where(temp2 > 0, temp2, np.inf).argmin()
    a = xb[m_index]
    xb[m_index] = xn[stopper]
    xn[stopper] = a

    B_ = res[:,xb[0]]
    B_ = B_.reshape(-1,1)
    for i in xb:
        y = res[:,i]
        y = y.reshape(-1,1)
        B_ = np.concatenate((B_,y),axis=1)
    B_ = np.delete(B_,0,1)
    B=B_
    if(np.linalg.det(B) == 0):
        flag=1
        print("unbounded")
        break
    B_inv = np.linalg.inv(B)
    need = np.matmul(B_inv,n_array)
#     print(need,B_inv)
    count = count+1

if(count == 1000):
    flag=1
    print("unbounded")

In [9]:
if(flag==0):
    flag3=0
    temp = np.matmul(B_inv,b)
    sol = np.zeros(len(N[0]))
    for i in range(len(xb)):
        if(xb[i]<len(N[0])):
            sol[xb[i]] = temp[i]
        else:
            if(temp[i]<0):
                print("infeasible solution")
                flag3=1
                break
    if(flag3==0):   # not infeasible
#         print(N)
        N = N.transpose()
#         print(sol[0])
        res = np.matmul(sol,N)
        flag1=0
#         print(res)
#         print(b[1][0])
        for i in range(len(res)):
            if(res[i] - b[i][0] > 0.0000001):
#                 print(res[i],b[i][0])
                flag1=1
#                 print("hello",i)
                break
        if(flag1!=1):
            opt_res = np.matmul(tcb,temp)
            print(opt_res)
            print(sol)
        else:
            print("hii")
            print("infeasible solution")

[90.]
[ 0. 30.]


In [10]:
print(sol)

[ 0. 30.]
